version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=inventaris
      - DB_USERNAME=root
      - DB_PASSWORD=12345
    networks:
      - app-network

  db:
    image: mysql:8.0  
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: inventaris
      MYSQL_ROOT_PASSWORD: 12345
    volumes:
      - dbdata:/var/lib/mysql
      - ./inventaris_skripsi.sql:/docker-entrypoint-initdb.d/inventaris_skripsi.sql
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
